version: '3'
services:
  postgres-dbt:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jaffle_shop
    volumes:
      - ./postgres-data-db-volume:/var/lib/postgresql/data
    ports:  
      - "6432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
