jaffle_shop:
  outputs:
    dev:
      dbname: jaffle_shop
      host: localhost
      pass: postgres
      port: 6432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
